# Generated by Django 6.1.1 on 2026-09-09 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True)),
                ('icon', models.CharField(default='🐦', max_length=10, verbose_name='آیکون (ایموجی)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True)),
                ('species', models.CharField(blank=True, max_length=150, verbose_name='گونه')),
                ('gender', models.CharField(choices=[('M', 'نر'), ('F', 'ماده'), ('U', 'نامشخص')], default='U', max_length=1, verbose_name='جنسیت')),
                ('age_months', models.PositiveIntegerField(default=0, verbose_name='سن (ماه)')),
                ('color', models.CharField(blank=True, max_length=80, verbose_name='رنگ')),
                ('care_level', models.CharField(choices=[('easy', 'مناسب مبتدی'), ('medium', 'نیاز به تجربه متوسط'), ('pro', 'نیاز به نگهدارنده حرفه\u200cای')], default='easy', max_length=10, verbose_name='سطح نگهداری')),
                ('can_talk', models.BooleanField(default=False, verbose_name='سخن\u200cگو')),
                ('image', models.ImageField(blank=True, null=True, upload_to='birds/', verbose_name='تصویر اصلی')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات کامل')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('is_featured', models.BooleanField(default=False, verbose_name='محصول ویژه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birds', to='shop.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'پرنده',
                'verbose_name_plural': 'پرنده\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='birds/gallery/', verbose_name='تصویر')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='shop.bird', verbose_name='پرنده')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'تصاویر گالری',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز')),
                ('comment', models.TextField(blank=True, verbose_name='نظر')),
                ('is_approved', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('bird', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.bird', verbose_name='پرنده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ['-created_at'],
                'unique_together': {('bird', 'user')},
            },
        ),
    ]
