# Generated by Django 6.1.1 on 2026-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='🐦', max_length=10, verbose_name='آیکون (ایموجی، اختیاری)'),
        ),
    ]
